# Generated by Django 6.1.1 on 2026-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_image_alter_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='production_date',
            field=models.DateField(null=True),
        ),
    ]
