<<<<<<< HEAD
# Generated by Django 5.2.7 on 2026-09-26 16:21
=======
# Generated by Django 6.1.1 on 2026-09-24 06:24
>>>>>>> 5f9ec7a (new commits)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_production_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='created_at',
<<<<<<< HEAD
            field=models.DateTimeField(auto_now_add=True, null=True),
=======
            field=models.DateField(auto_now_add=True, null=True),
>>>>>>> 5f9ec7a (new commits)
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_type',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Grocery', 'Grocery'), ('Fashion', 'Fashion')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated_at',
<<<<<<< HEAD
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
=======
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
>>>>>>> 5f9ec7a (new commits)
        ),
    ]
