# Generated by Django 5.2.7 on 2026-09-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmodel_created_at_productmodel_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_type',
            field=models.CharField(choices=[('Gadgets', 'Gadgets'), ('Devices', 'Devices'), ('Robots', 'Robots')], max_length=20, null=True),
        ),
    ]
